<?php
use Mmf\ACL\NoACL;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-21 at 14:56:46.
 */
class NoACLTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ACLWeb
     */
    protected $objectguest;
    protected $objectUser;
    protected $objectAdmin;
    protected $objectBadRoleName;
    protected $connection;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $authguest = $this->getMockBuilder('\Mmf\Auth\AuthInterface')
                ->disableOriginalConstructor()
                ->setMethods(array('authenticate', 'isAuthenticated', 'getUsername',
                    'getUserId', 'getRoleId', 'setRoleId', 'getRoleName', 'setUsername',
                    'setRoleName', 'setUserId', 'logout', '__construct'))
                ->getMock();

        $authguest->expects($this->any())
                ->method('getRoleName')
                ->willReturn('guest');

        $authUser = $this->getMockBuilder('Mmf\Auth\AuthInterface')
                ->disableOriginalConstructor()
                ->setMethods(array('authenticate', 'isAuthenticated', 'getUsername',
                    'getUserId', 'getRoleId', 'setRoleId', 'getRoleName', 'setUsername',
                    'setRoleName', 'setUserId', 'logout','__construct'))
                ->getMock();

        $authUser->expects($this->any())
                ->method('getRoleName')
                ->willReturn('user');

        $authAdmin = $this->getMockBuilder('Mmf\Auth\AuthInterface')
                ->disableOriginalConstructor()
                ->setMethods(array('authenticate', 'isAuthenticated', 'getUsername',
                    'getUserId', 'getRoleId', 'setRoleId', 'getRoleName', 'setUsername',
                    'setRoleName', 'setUserId', 'logout', '__construct'))
                ->getMock();

        $authAdmin->expects($this->any())
                ->method('getRoleName')
                ->willReturn('admin');

        $config = $this->getMockBuilder('Mmf\Parameter\ParametersInterface')
                ->disableOriginalConstructor()
                ->getMock();

        $config->method('get')
                ->will($this->returnCallback('callbackConfigACL'));

        $this->connection = new \Mmf\Model\PDO($config);

        $this->objectguest       = new NoACL($authguest, $this->connection);
        $this->objectUser        = new NoACL($authUser, $this->connection);
        $this->objectAdmin       = new NoACL($authAdmin, $this->connection);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        unset($this->objectguest);
    }

    /**
     * @covers \Mmf\ACL\NoACL::isAllowed
     * @covers \Mmf\ACL\NoACL::__construct
     * @group acl
     * @group db
     * @group modules
     * @group development
     * @group production
     */
    public function testIsAllowedguest() {
        $routingRule = $this->getMockBuilder('\Mmf\Routing\RoutingRuleAbstract')
                ->disableOriginalConstructor()
                ->setMethods(array('getRegularExpression', 'getController',
                    'getAction', 'getInput', 'getOutput',
                    'setRegularExpression', 'setController',
                    'setAction', 'setInput', 'setOutput', 'getMethod',
                    'setMethod'))
                ->getMock();

        $routingRule->expects($this->any())
                ->method('getController')
                ->willReturn('Product');

        $routingRule->expects($this->any())
                ->method('getAction')
                ->willReturn('show');

        $allowed = $this->objectguest->isAllowed($routingRule);
        $this->assertEquals(true, $allowed);
    }

    /**
     * @covers \Mmf\ACL\NoACL::isAllowed
     * @covers \Mmf\ACL\NoACL::__construct
     * @group acl
     * @group db
     * @group modules
     * @group development
     * @group production
     */
    public function testIsAllowedUserOtherAction() {
        $routingRule = $this->getMockBuilder('Mmf\Routing\RoutingRuleAbstract')
                ->disableOriginalConstructor()
                ->setMethods(array('getRegularExpression', 'getController',
                    'getAction', 'getInput', 'getOutput',
                    'setRegularExpression', 'setController',
                    'setAction', 'setInput', 'setOutput', 'getMethod',
                    'setMethod'))
                ->getMock();

        $routingRule->expects($this->any())
                ->method('getController')
                ->willReturn('Product');

        $routingRule->expects($this->any())
                ->method('getAction')
                ->willReturn('otheraction');

        $allowed = $this->objectUser->isAllowed($routingRule);
        $this->assertEquals(true, $allowed);
    }

    /**
     * @covers \Mmf\ACL\NoACL::isAllowed
     * @covers \Mmf\ACL\NoACL::__construct
     * @group acl
     * @group db
     * @group modules
     * @group development
     * @group production
     */
    public function testIsAllowedUser() {
        $routingRule = $this->getMockBuilder('Mmf\Routing\RoutingRuleAbstract')
                ->disableOriginalConstructor()
                ->setMethods(array('getRegularExpression', 'getController',
                    'getAction', 'getInput', 'getOutput',
                    'setRegularExpression', 'setController',
                    'setAction', 'setInput', 'setOutput', 'getMethod',
                    'setMethod'))
                ->getMock();

        $routingRule->expects($this->any())
                ->method('getController')
                ->willReturn('Client');

        $routingRule->expects($this->any())
                ->method('getAction')
                ->willReturn('save');

        $allowed = $this->objectUser->isAllowed($routingRule);
        $this->assertEquals(true, $allowed);
    }

    /**
     * @covers \Mmf\ACL\NoACL::isAllowed
     * @covers \Mmf\ACL\NoACL::__construct
     * @group acl
     * @group db
     * @group modules
     * @group development
     * @group production
     */
    public function testAllowedAdmin() {
        $routingRule = $this->getMockBuilder('Mmf\Routing\RoutingRuleAbstract')
                ->disableOriginalConstructor()
                ->setMethods(array('getRegularExpression', 'getController',
                    'getAction', 'getInput', 'getOutput',
                    'setRegularExpression', 'setController',
                    'setAction', 'setInput', 'setOutput', 'getMethod',
                    'setMethod'))
                ->getMock();

        $routingRule->expects($this->any())
                ->method('getController')
                ->willReturn('Product');

        $routingRule->expects($this->any())
                ->method('getAction')
                ->willReturn('show');

        $allowed = $this->objectAdmin->isAllowed($routingRule);
        $this->assertEquals(true, $allowed);
    }

    /**
     * @covers \Mmf\ACL\NoACL::isAllowed
     * @covers \Mmf\ACL\NoACL::__construct
     * @group acl
     * @group db
     * @group modules
     * @group development
     * @group production
     */
    public function testAllowedAdminParentRole() {
        $routingRule = $this->getMockBuilder('Mmf\Routing\RoutingRuleAbstract')
                ->disableOriginalConstructor()
                ->setMethods(array('getRegularExpression', 'getController',
                    'getAction', 'getInput', 'getOutput',
                    'setRegularExpression', 'setController',
                    'setAction', 'setInput', 'setOutput', 'getMethod',
                    'setMethod'))
                ->getMock();

        $routingRule->expects($this->any())
                ->method('getController')
                ->willReturn('Client');

        $routingRule->expects($this->any())
                ->method('getAction')
                ->willReturn('save');

        $allowed = $this->objectAdmin->isAllowed($routingRule);
        $this->assertEquals(true, $allowed);
    }
}

function callbackConfigACL() {
    $functionArguments = func_get_args();
    $conection1 = array('host' => 'localhost', 'port' => '8889', 'name' => 'marketplace',
        'user' => 'root', 'pass' => 'root');

    $conection2 = array('host' => 'localhost', 'port' => '8889', 'name' => 'marketplace1',
        'user' => 'root', 'pass' => 'root');

    $return = array('db_default' => $conection1, 'db_secondary' => $conection2);
    return $return[$functionArguments[0]];
}
